services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "6969:5432"
    environment:
      POSTGRES_USER: bugfinderr
      POSTGRES_PASSWORD: bugfi
      POSTGRES_DB: fakestore
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
